name: PrivyaRepoScan

on: [push]
# on: [pull_request]
# on: [push,pull_request]
# on:
#   schedule:
#     - cron: '*/5 * * * *'

jobs:
  api-actions:
    runs-on: ubuntu-latest
    steps:
    
    # Step 0: Echo env vars
    - uses: actions/checkout@v1
    - name: Echo env vars
      run: |
        echo '${{ toJSON(github) }}' 
    
    # Step 1: Run Privya Scan
    - name: Run Privya Scan
      id: scan
      uses: ./.github/actions/docker
    # continue-on-error: true
      with:
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}        
      env:
        ORG_NAME: youshallworknow
        SCAN_MAX_OK_SCORE: 7
        
